// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Token struct {
	Token string `json:"token"`
}

type UserID struct {
	ID string `json:"id"`
}

type WishID struct {
	ID int `json:"id"`
}
